name = "fmi-cal-worker"
main = "src/index.js"
compatibility_date = "2024-12-01"

[[routes]]
pattern = "cal.rdobre.ro"
custom_domain = true

[[kv_namespaces]]
binding = "CAL_CONFIGS"
id = "b4c1020e854244f29f51bb29cb87d5c1"

[vars]
ORIGIN_URL = "https://orar-fmi.rdobre.ro"
