name = "fmi-cal-worker"
main = "src/index.js"
compatibility_date = "2024-12-01"

routes = [
  { pattern = "cal.rdobre.ro/*", zone_name = "rdobre.ro" }
]

[vars]
ORIGIN_URL = "https://orar-fmi.rdobre.ro"
